### ISSUE TITLE
Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

### ISSUE THREAD

**Issue by dpgeekzero** [poseidon/terraform-provider-matchbox#45]
Just updated my local terraform client to v0.12.0 and receiving compatibility errors, even after updating the plugin.  Is there something else I needed to do?

```
> find .terraform

.terraform
.terraform/plugins
.terraform/plugins/linux_amd64
.terraform/plugins/linux_amd64/terraform-provider-template_v2.1.2_x4
.terraform/plugins/linux_amd64/lock.json
.terraform/plugins/linux_amd64/terraform-provider-matchbox_v0.2.3

> terraform version

Terraform v0.12.0
+ provider.matchbox v0.2.3
+ provider.template v2.1.2

> terraform validate

Error: Failed to instantiate provider "matchbox" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

**Comment by dghubble** [comment]
Check [CHANGES](https://github.com/poseidon/terraform-provider-matchbox/blob/master/CHANGES.md) to see that a compatibility change was made a few weeks ago. You can either compile from source or wait for an official release to start trialing Terraform v0.12.0.
